# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.6.0"

gem "puma", "~> 3.11"
gem "rails", "~> 5.2.2"
gem "sqlite3"

gem "dry-view", path: "../.."
gem "slim"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "web-console", ">= 3.3.0"
end
